[tool.poetry]
name = "brieffenster-generator"
version = "0.1.0"
description = ""
authors = ["Jonas Groeger <jonas@huntun.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^3.0.2"
reportlab = "^4.0.4"
Pillow = "^10.3.0"
gunicorn = "^21.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
