[tool.poetry]
name = "brieffenster-generator"
version = "0.1.0"
description = ""
authors = ["Jonas Groeger <jonas@huntun.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.3.2"
reportlab = "^3.5.67"
Pillow = "^9.3.0"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
